### ISSUE TITLE
Work?

### ISSUE THREAD

**Issue by ghost** [SOLOPlugins-Nukkit/SOLOLand#3]
Hello @solo5star . What commands have this plugin ? Not work /is or /skyblock..

Please,you can add commands in english?

**Comment by solo5star** [comment]
I'm sorry, but English is not support yet. I will add English at next version.

**Comment by ghost** [comment]
Please man....

**Comment by ghost** [comment]
@solo5star Please you can add now commands in eng?

**Comment by shdudwns** [comment]
He left Minekraft and SOLOLand is dead!
@NycuRO

**Comment by ghost** [comment]
LOL 2016 LMAO
